### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by edobry** [staltz/ssb-room#1]
Hey Andre,

Super cool new project! Tried to create my own room, but after following the steps, the container wouldn't start. When running `docker logs room`, I see this error:

```
Error: EACCES: permission denied, open '/home/node/.ssb/secret'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.exports.createSync (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-keys/storage.js:104:8)
    at Object.exports.loadOrCreateSync (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-keys/index.js:89:20)
    at setDefaults (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-config/defaults.js:71:27)
    at module.exports (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-config/inject.js:7:16)
    at Object.<anonymous> (/home/node/.npm-global/lib/node_modules/ssb-room/config.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

Did I miss a step maybe?

Thanks!

**Comment by edobry** [comment]
Nevermind, this was my mistake; I moved the data directory after I created and `chown`d it, but didn't modify `create-room` to account for that, so when I ran it, it created a new data directory at the original location, but not owned by `1000`!
