### ISSUE TITLE
Docker Container - Continually Restarting

### ISSUE THREAD

**Issue by imattau** [staltz/ssb-room#23]
Following the Docker pull install method  from the manual install documentation - the docker container status is continually restarting.

The container logs show:

Error: EACCES: permission denied, open '/home/node/.ssb/secret'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.exports.createSync (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-keys/storage.js:104:8)
    at Object.exports.loadOrCreateSync (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-keys/index.js:89:20)
    at setDefaults (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-config/defaults.js:71:27)
    at module.exports (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-config/inject.js:7:16)
    at Object.<anonymous> (/home/node/.npm-global/lib/node_modules/ssb-room/config.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

*Note - when attempting to install from git - The install fails.*

Install on Digital Ocean - Debian 9 Droplet ($5)

**Comment by austinfrey** [comment]
@imattau for what it's worth I was unable to reproduce. I followed the manual install instructions on a $5 digital ocean droplet and the room is up and running.

**Comment by imattau** [comment]
@austinfrey I managed to get it working - Had to use the root login (and su as debian for the folder creation) for the install.

Seems it didn't like sudo'ing...

Now just having some port closed issues... :(
